### ISSUE TITLE
Salary computation not working as expected

### ISSUE THREAD

**Issue by olivierb2** [OCA/payroll#29] opened 2022-02-10 16:55 UTC
## Module
payroll

## Describe the bug
Adding a manual value into "Salary Computation" doesn't recalculate other lines.

## To Reproduce
**Affected versions**: tested on Odoo 13.0 and 14.0

1. Create new payslip
2. Click on "Compute Sheet" button to populate Salary Computation
3. Click on "Edit"
4. Click "Add a line"
5. Add new item "Bonus"

**Expected behavior**
While "Bonus" has code than BASIC, I expected to have all other lines computed, like GROSS which is supposed to be categories.BASIC + categories.ALW.

**Comment by nimarosa** [comment] 2022-02-11 00:54
Yes, it's a known bug. I have a patch for it, will make a new PR on that on the 14.0 branch to fix it.

**Comment by housemateguy** [comment] 2022-02-12 10:57
Will there be a fix for this in 13.0 ?

**Comment by olivierb2** [comment] 2022-02-12 13:55
Same for me, patch for 13.0 is also useful for me as my company is currently still on 13.0.

**Comment by nimarosa** [comment] 2022-05-31 21:48
@appstogrow Do you want to work in this with me? As you are also doing a localization for payroll. This is a known error but i think it's difficult to patch and maybe we will have to change some of the core functionality.

**Comment by ghost** [comment] 2022-06-01 14:38
@nimarosa Does your patch work for 14.0 also after the changes done in the latest PRs? If you share your patch, anyone can contribute. This issue is low priority for me, but probably I can review and give feedback.

@olivierb2 and @housemateguy, when will you migrate to 14.0?

**Comment by olivierb2** [comment] 2022-06-01 15:00
I'm not sure to migrate to 14.0 at this stage, I have reconcile feature missing on my testing database, I'm not sure why Odoo remove features each time they do new version :-(

**Comment by ghost** [comment] 2022-06-01 15:59
@olivierb2 Did you try the new OCA module [account_reconciliation_widget](https://github.com/OCA/account-reconcile/tree/14.0/account_reconciliation_widget)?

**Comment by olivierb2** [comment] 2022-06-01 16:26
Not sure it's the best place to discuss about this, but yes, I tried it. But logic is completely changed and looks much less convenient than before.

**Comment by nimarosa** [comment] 2022-06-01 16:53
> @nimarosa Does your patch work for 14.0 also after the changes done in the latest PRs? If you share your patch, anyone can contribute. This issue is low priority for me, but probably I can review and give feedback.
> 
> @olivierb2 and @housemateguy, when will you migrate to 14.0?

I have a partial patch. Will make a PR so we can work in it. But it has to be tested because it changes the way of making the calculations. 

It will be great also to make 14.0 the main branch of this repo. It has a lot of new things in the 14.0 branch which is the branch i'm working on.

**Comment by pedrobaeza** [comment] 2022-06-01 16:54
@simahawk please make 14.0 the default branch

**Comment by simahawk** [comment] 2022-06-14 09:45
> @simahawk please make 14.0 the default branch

Sorry for being late at the party... I got covid and I've been off for a while :sweat_smile: 
It's done.

**Comment by pedrobaeza** [comment] 2022-06-14 09:47
Thanks, and hope that you are fine already.

**Comment by nimarosa** [comment] 2022-08-29 20:34
@pedrobaeza Can you close this? Since it's not relevant and not a bug due to the changes in #60

**Closed as completed** 2022-08-29 20:35 UTC
Labels: bug
