### ISSUE TITLE
Payslip - Details By Salary Rule Category

### ISSUE THREAD

**Issue by ghost** [OCA/payroll#52] opened 2022-08-16 19:00 UTC
hr.payslip has two fields with one2many relationship to hr.payslip.line:
- line_ids
- details_by_salary_rule_category - showing only lines with category_id, which is a required field
So these fields are identical.

`details_by_salary_rule_category` is found only seven times in the code. Can we remove this field and replace with line_ids?

Why is there a separate page "Details By Salary Rule Category" in the payslip? All the info is also in "Salary Computation", right?

**Comment by nimarosa** [comment] 2022-08-16 20:25
@appstogrow Glad you open this thread. This is something i noticed long time ago but i couldn't explain why details_by_salary_rule_category was there. It shows the same data but ordered by category_id. It don't make sense to me. 
For me this field was ment for other uses and it never got finished. I have two thoughts about what to do: 

1. We remove completely the  details_by_salary_rule_category from the module, since the way its works it's not helpful at all. If we do that, we have to adapt the default report because it's using that method to get the lines in order (maybe just changing the method and reordering the lines its okay). Then i don't think that method is used in other place that the report.  
 
2. When i just started using the module i thought that details_by_salary_rule_category was grouping the lines amounts into each category associated. So you can have a method that accumulates the amounts of payslip_lines in each category, giving you an accumulated total for each category. 
I think this functionality can be helpful because sometimes you need the category totals for a payslip from outside the model => meaning that user will need to access to category totals outside the salary_rules, so i think this is what this method is intended for. **What about if we implement this functionality to make details_by_salary_rule_category display accumulated values of the categories? I think it can be done and i have some approaches to do it. **

**What do you think?**

**Comment by dantrix** [comment] 2022-08-17 20:23
> hr.payslip has two fields with one2many relationship to hr.payslip.line:
> 
> * line_ids
> * details_by_salary_rule_category - showing only lines with category_id, which is a required field
>   So these fields are identical.
> 
> `details_by_salary_rule_category` is found only seven times in the code. Can we remove this field and replace with line_ids?
> 
> Why is there a separate page "Details By Salary Rule Category" in the payslip? All the info is also in "Salary Computation", right?

@appstogrow Hello, in the Calculation tab the lines are shown ordered according to their ID, which does not allow an analysis of the payment by the Payroll Analyst, Having managed payroll for years, think that if it adds something of value, it may not be a great contribution, but if it is functional.

**Comment by dantrix** [comment] 2022-08-17 20:27
> @appstogrow Glad you open this thread. This is something i noticed long time ago but i couldn't explain why details_by_salary_rule_category was there. It shows the same data but ordered by category_id. It don't make sense to me. For me this field was ment for other uses and it never got finished. I have two thoughts about what to do:
> 
> 1. We remove completely the  details_by_salary_rule_category from the module, since the way its works it's not helpful at all. If we do that, we have to adapt the default report because it's using that method to get the lines in order (maybe just changing the method and reordering the lines its okay). Then i don't think that method is used in other place that the report.
> 2. When i just started using the module i thought that details_by_salary_rule_category was grouping the lines amounts into each category associated. So you can have a method that accumulates the amounts of payslip_lines in each category, giving you an accumulated total for each category.
>    I think this functionality can be helpful because sometimes you need the category totals for a payslip from outside the model => meaning that user will need to access to category totals outside the salary_rules, so i think this is what this method is intended for. **What about if we implement this functionality to make details_by_salary_rule_category display accumulated values of the categories? I think it can be done and i have some approaches to do it. **
> 
> **What do you think?**

@nimarosa The sum of amounts by category is normally handled by the concepts Gross, Net, among others. In addition, the sum of categories involves the bases for different withholdings, so it may be very difficult to delve into it.

**Comment by nimarosa** [comment] 2022-08-17 20:36
@dantrix 
The lines in the calculation tab are ordered by the sequence, not ID. The sequence it's the order the rules are calculated so it makes sense to display them in that way. Anyways, if the problem is the order, we can make some order buttons or filters but i think the order who the user will want the most is the sequence order, like it works right now. 

About your second comment, i did not understand what you are trying to say. What i'm proposing is using the details by rule category tab to display accumulated values, it will not change any current behaviour of the categories or anything like that. 
The concepts Gross, Net, etc that you mention are salary_rules which are created by the user of the module, so, depending of the way of calculating payroll every business will do it different. 
Sum categories will be the base for calculation of salary rules, i understand, but what i'm proposing nothing has to do with that behavior, the method details_by_salary_rule_category it's just a computed field which we can modify to show anything we want, it don't involve category sum methods.

**Comment by dantrix** [comment] 2022-08-17 20:51
@nimarosa My bad, sequence instead ID.

@appstogrow the order for category is functional, maybe no is great value, but ,we have it.

**Comment by ghost** [comment] 2022-08-21 13:02
Regarding the first response from @nimarosa 

1. I suggest to "remove completely the details_by_salary_rule_category from the module" or mark it as DEPRECATED and remove in next version.

2. When will a user need "access to category totals outside the salary_rules"? Could this be implemented with pivot view?

**Comment by nimarosa** [comment] 2022-08-21 13:28
@appstogrow A user will need to access totals of the categories outside of salary rules for example when you are using categories to accumulate amounts of different rule types. For example one of the use cases I have developed is that we use salary rules categories sum to generate government declaration of the monthly payslips. So in that case we generate a txt that must inform amounts by salary rule category to our government tax revenue systems. 
I have a custom implementation that so that in the localization but maybe can be useful to allow the user see this values in payslip form for a manual check of the sums or to debug salary rules. 

Anyways yesterday I was looking into that topic and realized that in the first version of this module (pre odoo 11) this method was used to display the tree view grouped by category_id in that form (like a filtered view does). Then in odoo 11 odoo removes the feature of grouping views inside forms so that's why now the table is identical to the line_ids one. If you look into views xml you will note that details_by_salary_rule_category table has the attribute groupby=category_id which is there but as odoo removed this function it does nothing. 

Also notes that in the view we have a context to filter in this method only the lines that have appears_on_payslip set to true. So this method in the past also shown only salary lines that appears in the payslip. Like the grouping functionality, this context no longer works because odoo changed the way this tables are generated. We can fix it doing a filter in the function directly but the grouped view will not be possible if we don't have a widget to do it. 

This given me an idea to use this tab to only show rules that have appears_on_payslip true , so I will make a PR with this functionality and maybe we can change the name of the function. Also I noted that all the functionality of child and parent salary rules today is not used since all rules and fetched and ordered by sequence, we don't have a view to see child salary rules in the line form and also is not diferenciated in the calculation table. So this PR also will include my approach to give the child and parent salary rules a purpose modifying the views so we can distinct, show or hide and manipulate the form to make this usable again. 

Hope I made clear about it because it took me time to realice what was happening with this method and also with parent and child salary rules. 

Finally I know it don't concern to this issue but I comment it here, in my next PR my intention is to make this changes to see what you guys think of that approach that will make this Method usable again and also support hierarchy in the views. For this we will change the way we use now the views. 

Finally I want to comment that I had access to a odoo enterprise installation and noted that the enterprise module does not allow manual editing of the salary computation form. This make sense to me because the idea is the rules to be computed not manually added. In enterprise only name of the line is editable. With that said, I think we should replicate that behavior since it will fix the bug issue (#29) and removing that will allow us to use custom methods to filter the table (and not line_ids obj) and provide a more advanced filter functionality for the table (show or hide child rules for ex. But not limited to). 

This ideas is what i found when I was checking the code about this issue. I will submit a PR so you can see and test the approach and let me know if it's something you would like to see in the future of the module. If not we can always continue doing setting-managed functionalities so that way the module is more flexible. 

Kind regards

**Comment by ghost** [comment] 2022-08-21 14:34
@nimarosa So in short:
One use case of category totals is to check that the government tax declaration is correct.
Before 11.0, the view showed category totals of payslip lines which appears_on_payslip.
You want to fix this in a PR which also fixes parent/child rules.
Payslip lines are readonly in Enterprice (except for name field) and you like this.

Keep in mind that the payroll should be easy to understand and use. I think parent/child rules is complicated. But maybe I will like it when I understand it. :)

**Comment by nimarosa** [comment] 2022-08-21 14:48
@appstogrow yes, everything correct. Maybe today I will finish the first version of the PR and we can continue with suggestions and improvements there. 

About child rules, yes I agree with you that today are confusing and if you look at the code they don't have a purpose because the method that calculates rules fetches all and order by sequence so today the functionality it's not used. Also we have no views that use that anyways. 

My approach will be to make the computation table in a way we can distinct the payslip lines that are child of a parent one, choose if you want to see it or not in the table (with a Boolean) and also showing child in payslip_lines pop up form that opens when you click a rule. As payslip_line is a inherited model of salary_rule we can use the parent field to propagate child rules to payslip lines.

With that changes (and maybe more that we can think in the PR) we can use child and parent salary rules to make "auxiliar calculations" , that means that for me the functionality has to be that child salary rules are auxiliar calculations that are used to calculate parent salary rule value and in most cases they don't appear in payslip. 

We can see this approach and improve it in the PR and if we see usefulness in it we merge it or we can remove parent / child functionality from the module because it really don't make any difference if we don't have views that shows this parent objects and do something different with them. 

Will try to explain the approach in detail in the PR with images so we can discuss if it we will useful. For me it is, I really don't use child/parent rules today but with this approach I think will be useful for auxiliar calculations and also for leaving a log of the intermediate calculation of a SR. 

Keep posted I think I can have it today because I've already started.

**Comment by mtelahun** [comment] 2022-08-21 15:10
On 21/08/2022 17:34, Henrik Norlin wrote:
> Keep in mind that the payroll should be easy to understand and use. I 
> think parent/child rules is complicated. But maybe I will like it when 
> I understand it. :) 


https://addisbiz.com/blog/67-salary-income-tax-calculation-in-ethiopia-pension-gross-salary-and-net-salary-calculator-with-examples/

https://github.com/mtelahun/l10n-ethiopia/blob/14.0/l10n_et_payroll_FIT2016/data/payroll_data.xml

**Comment by mtelahun** [comment] 2022-08-21 15:15
Sorry, it may not be evident from just the links but parent/child rules are convenient for doing calculations like progressive income taxes.

**Comment by nimarosa** [comment] 2022-08-21 15:50
@mtelahun that's exactly the use case I was thinking. Having views to group the child rules and payslip lines then its a good feature to develop.

**Comment by ghost** [comment] 2022-08-21 19:32
Previously I tested similar approach with [l10n_be_hr_payroll](https://github.com/odoo/odoo/blob/12.0/addons/l10n_be_hr_payroll/data/hr.salary.rule.csv). With 1400 rules, it took a long time to process the data on each module update. [The Norwegian tax tables have almost 290.000 lines](https://www.skatteetaten.no/en/rates/deduction-tables-in-text-format/), and they change every year. So I created a separate model for them, and I have one salary rule searching the tax model for the right tax value. If I were to implement this with 290.000 child rules, I suppose the calculations would be slow...

**Comment by nimarosa** [comment] 2022-08-21 20:25
@appstogrow i don't know about @mtelahun approach. What I mean about the child rules i think of it to be used in auxiliary calculations for a rule that needs to calculate its result in micro steps. For example in my country this type of calculations are for income tax when the employee can have different deductions that affect the base amount of the final calculation. 

For tax rates and values of labor union I have the same approach as you Henrik, I have one salary rule that search for the right value according to payslip dates and data. And I think that is the right approach, making one salary rule in countries where the rates and values change every year it's not practical at all. Also I use the model salary_rule_parameter to fetch some of this values and for labor unions I have another different module that have functions that return the values according to the dates.

**Comment by nimarosa** [comment] 2022-08-31 19:29
@pedrobaeza Please close, this discussion is resolved by the approach adopted in #60

**Closed as completed** 2022-08-31 20:08 UTC
Labels: enhancement
